- hosts: managers
  become: true
  become_method: runas
  roles:
  - role: passwordless-sudo
    vars:
      user: kiran11kalsi
  - docker
  - manager
  

- hosts: workers
  become: true
  roles:
  - docker
  - worker